### ISSUE TITLE
要不要开发英文版本？

### ISSUE THREAD

**Issue by DaZuiZui** [DaZuiZui/ZuiOJ#1]
要不要开发英文版本？

**Comment by DaZuiZui** [comment]
想了下，下个月准备做英文版本为开源准备

**Comment by C9chengxuyuan** [comment]
Hope to develop an English version and update your readme file

**Comment by DaZuiZui** [comment]
> 希望开发一个英文版本并更新你的readme文件

好的我会尽快更新
