### ISSUE TITLE
建议改善榜单系统。It is recommended to improve the list system.

### ISSUE THREAD

**Issue by Kuyeyeyeyeye** [DaZuiZui/ZuiOJ#10]
不得不说这个项目是一个出色的项目，建议改善榜单系统，可以查看每个用户完成了哪些问题，可以查看每个题花费了多长时间，目前的榜单系统仿佛没有展示。
I have to say that this project is an excellent project. It is recommended to improve the list system. You can check which questions each user has completed and how long each question took. The current list system does not seem to show it.

**Comment by DaZuiZui** [comment]
抱歉，目前我没有想到更好的解决方案，我想在日后进程我将选择缓存等机制进行优化
