### ISSUE TITLE
I want to ask a question about the judgment code　想询问下判断代码的问题

### ISSUE THREAD

**Issue by C9chengxuyuan** [DaZuiZui/ZuiOJ#4]
For example, if we want to print a Hello World, if we are in 洛谷OJ, it is correct to use system.out.println() or system.out.print() or printf in C language.
But use your OJ system to print if it is system.out.println(), the result returned by your judger is helloworld\n
If you are using system.out.print() return helloworld
I don't know if my question is well stated, normally both cases are true. But if the answer stored in the database is helloworld\n, then it is wrong to use system.out.print() and printf in C language.
I don't know if this problem is a loophole in the system or this oj feature
My expressive skills are poor hope someone understands my problem.

比如我们让打印一个Hello World，如果我们在洛谷OJ把，使用system.out.println（）或者使用system.out.print（）或者使用C语言　printｆ都是正确的，
但是使用你的ＯＪ系统打印如果是system.out.println（）则你的判题器返回的结果是helloworld\n
如果使用的是system.out.print（）则返回helloworld
我不知道我的问题是否陈述清楚，正常来说这两种情况都是正确的。但是如果数据库存入的答案是helloworld\n那么使用system.out.print（）和Ｃ语言的printｆ就是错误的。
不知道这个问题是该系统存在的漏洞还是此ｏｊ特性
我的表达能力很差希望能理解我的问题。

**Comment by DaZuiZui** [comment]
This is indeed a bug in my System,which i will fix soon,Thank u for ur attention

**Comment by DaZuiZui** [comment]
这的确是我系统的一个bug，我很快就会解决。感谢您的关注！

**Comment by C9chengxuyuan** [comment]
感谢您的回复
