### ISSUE TITLE
题解的bug question answer bug

### ISSUE THREAD

**Issue by Kuyeyeyeyeye** [DaZuiZui/ZuiOJ#9]
如果题目类型的是比赛题目的话，我们是没有按钮进入题解页面，但是我可以通过控制Url参数进入题解页面，创建题解和浏览题解。
If the question type is a competition question, we don't have a button to enter the solution page, but I can enter the solution page by controlling the Url parameter, create a solution and browse the solution.

**Comment by DaZuiZui** [comment]
Hi can u describe it in more detail?

**Comment by DaZuiZui** [comment]
你好，能描述的详细点吗？

**Comment by Kuyeyeyeyeye** [comment]
如当我们比赛题目的编号是10086，那么我可以通过/h/cn/question/questionAnser?id=10086强行进入题解页面

**Comment by DaZuiZui** [comment]
Ok I got it, I'll fix it as soon as possible，thank u
